"""usuarios

Revision ID: 965f88cd6b21
Revises: 
Create Date: 2026-08-28 18:37:40.091104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '965f88cd6b21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.drop_table('atividades_aluno')
    op.drop_table('conteudos')
    op.drop_table('mensagens')
    op.drop_table('aluno_conquista')
    op.drop_table('atividades')
    op.drop_table('ranking')
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('matricula'))

    op.drop_table('alunos')
    op.drop_table('professores')
    op.drop_table('niveis')
    op.drop_table('conquistas')
    op.drop_table('aluno_turma')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('codigo_turma'))

    op.drop_table('turmas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas',
    sa.Column('id_turma', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_turma', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('codigo_turma', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('disciplina', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ano_letivo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_professor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_professor'], ['professores.id_professor'], name=op.f('turmas_ibfk_1')),
    sa.PrimaryKeyConstraint('id_turma'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('codigo_turma'), ['codigo_turma'], unique=True)

    op.create_table('usuarios',
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('tipo_usuario', mysql.ENUM('aluno', 'professor', 'admin'), nullable=False),
    sa.Column('genero', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_nascimento', sa.DATE(), nullable=True),
    sa.Column('foto', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_cadastro', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.create_table('aluno_turma',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_turma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], name=op.f('aluno_turma_ibfk_1')),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id_turma'], name=op.f('aluno_turma_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conquistas',
    sa.Column('id_conquista', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('xp_recompensa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('icone', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_conquista'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('niveis',
    sa.Column('id_nivel', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nivel', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xp_necessario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recompensa_moedas', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_nivel'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('professores',
    sa.Column('id_professor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('titulacao', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('professores_ibfk_1')),
    sa.PrimaryKeyConstraint('id_professor'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('alunos',
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('matricula', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('nivel_atual', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('xp_total', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('moedas', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name=op.f('alunos_ibfk_1')),
    sa.PrimaryKeyConstraint('id_aluno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('matricula'), ['matricula'], unique=True)

    op.create_table('ranking',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pontuacao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('posicao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_turma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], name=op.f('ranking_ibfk_1')),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id_turma'], name=op.f('ranking_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('atividades',
    sa.Column('id_atividade', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('xp_recompensa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dificuldade', mysql.ENUM('facil', 'medio', 'dificil'), nullable=True),
    sa.Column('data_limite', sa.DATE(), nullable=True),
    sa.Column('id_turma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id_turma'], name=op.f('atividades_ibfk_1')),
    sa.PrimaryKeyConstraint('id_atividade'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('aluno_conquista',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_conquista', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_conquista', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], name=op.f('aluno_conquista_ibfk_1')),
    sa.ForeignKeyConstraint(['id_conquista'], ['conquistas.id_conquista'], name=op.f('aluno_conquista_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mensagens',
    sa.Column('id_mensagem', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('remetente_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destinatario_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mensagem', mysql.TEXT(), nullable=True),
    sa.Column('data_envio', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id_usuario'], name=op.f('mensagens_ibfk_2')),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id_usuario'], name=op.f('mensagens_ibfk_1')),
    sa.PrimaryKeyConstraint('id_mensagem'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conteudos',
    sa.Column('id_conteudo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('arquivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_publicacao', sa.DATE(), nullable=True),
    sa.Column('id_turma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_turma'], ['turmas.id_turma'], name=op.f('conteudos_ibfk_1')),
    sa.PrimaryKeyConstraint('id_conteudo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('atividades_aluno',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_atividade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nota', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('xp_ganho', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.ENUM('pendente', 'entregue', 'corrigido'), nullable=True),
    sa.Column('data_entrega', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], name=op.f('atividades_aluno_ibfk_1')),
    sa.ForeignKeyConstraint(['id_atividade'], ['atividades.id_atividade'], name=op.f('atividades_aluno_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
