"""adicionando as tabelas do projeto da patricia

Revision ID: fabe1ff83c60
Revises: 965f88cd6b21
Create Date: 2026-09-08 17:17:36.940905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabe1ff83c60'
down_revision = '965f88cd6b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conquistas_fisica',
    sa.Column('id_conquista', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('criterio', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('xp_recompensa', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id_conquista'),
    sa.UniqueConstraint('criterio')
    )
    op.create_table('fases_jogo_fisica',
    sa.Column('id_fase', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_atividade', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('dificuldade', sa.String(length=20), nullable=True),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pontuacao_maxima', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('configuracao', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id_fase')
    )
    op.create_table('niveis_fisica',
    sa.Column('id_nivel', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp_necessario', sa.Integer(), nullable=False),
    sa.Column('recompensa_moedas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id_nivel'),
    sa.UniqueConstraint('nivel')
    )
    op.create_table('aluno_conquista_fisica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_conquista', sa.Integer(), nullable=False),
    sa.Column('data_conquista', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_conquista'], ['conquistas_fisica.id_conquista'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno', 'id_conquista', name='uq_aluno_conquista')
    )
    op.create_table('progresso_fase_fisica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_fase', sa.Integer(), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('estrelas', sa.Integer(), nullable=True),
    sa.Column('xp', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_fase'], ['fases_jogo_fisica.id_fase'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno', 'id_fase', name='uq_progresso_fase')
    )
    op.create_table('modulos_fisica',
    sa.Column('id_modulo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_conteudo', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('dificuldade', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('corpo', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_conteudo'], ['conteudos.id_conteudo'], ),
    sa.PrimaryKeyConstraint('id_modulo')
    )
    op.create_table('atividades_fisica',
    sa.Column('id_atividade', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('dificuldade', sa.String(length=20), nullable=True),
    sa.Column('xp_recompensa', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('resposta_correta', sa.Float(), nullable=True),
    sa.Column('tolerancia', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos_fisica.id_modulo'], ),
    sa.PrimaryKeyConstraint('id_atividade')
    )
    op.create_table('exemplos_fisica',
    sa.Column('id_exemplo', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('dados', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos_fisica.id_modulo'], ),
    sa.PrimaryKeyConstraint('id_exemplo')
    )
    op.create_table('formulas_fisica',
    sa.Column('id_formula', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('expressao', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('calc', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos_fisica.id_modulo'], ),
    sa.PrimaryKeyConstraint('id_formula')
    )
    op.create_table('progresso_modulo_fisica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('progresso', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('concluido', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_modulo'], ['modulos_fisica.id_modulo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno', 'id_modulo', name='uq_progresso_modulo')
    )
    op.create_table('alternativas_fisica',
    sa.Column('id_alternativa', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_atividade', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=300), nullable=False),
    sa.Column('correta', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['id_atividade'], ['atividades_fisica.id_atividade'], ),
    sa.PrimaryKeyConstraint('id_alternativa')
    )
    op.create_table('dicas_fisica',
    sa.Column('id_dica', sa.Integer(), nullable=False),
    sa.Column('id_atividade', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_atividade'], ['atividades_fisica.id_atividade'], ),
    sa.PrimaryKeyConstraint('id_dica')
    )
    op.create_table('progresso_atividade_fisica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('id_atividade', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('xp_ganho', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'concluida'"), nullable=False),
    sa.Column('tentativas', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('dicas_utilizadas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('data_entrega', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_atividade'], ['atividades_fisica.id_atividade'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno', 'id_atividade', name='uq_progresso_atividade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresso_atividade_fisica')
    op.drop_table('dicas_fisica')
    op.drop_table('alternativas_fisica')
    op.drop_table('progresso_modulo_fisica')
    op.drop_table('formulas_fisica')
    op.drop_table('exemplos_fisica')
    op.drop_table('atividades_fisica')
    op.drop_table('modulos_fisica')
    op.drop_table('progresso_fase_fisica')
    op.drop_table('aluno_conquista_fisica')
    op.drop_table('niveis_fisica')
    op.drop_table('fases_jogo_fisica')
    op.drop_table('conquistas_fisica')
    # ### end Alembic commands ###
